---
- name: Ensure .m2 exists
  file:
    path: "{{ ansible_env.HOME }}/.m2"
    state: directory
    owner: "{{ ansible_env.USER }}"

- name: Upload maven global settings file
  template:
    src: settings.xml
    dest: "{{ ansible_env.HOME }}/.m2/settings.xml"
